---
-
# Above - sign indicates a list item. 
 
  # Target: where our play will run and options it will run with
  hosts: wingrp
  #gather_facts: false

  # Variable: variables that will apply to the play, on all target systems
  vars: 

  # Task: the list of tasks that will be executed within the playbook
  tasks:
    - name: create dir in remote system
      win_file:
       path: C:\wingrp
       state: directory
    - name: copy the files from this to remote
      win_copy:
        src: Test.ps1
        dest: C:/wingroup/Text.ps1
    
  # Handlers: handlers that are executed as a notify key from a task

  # Roles: list of roles to be imported into the play

# Three dots indicate the end of a YAML document
#ansible-playbook 01tasks.yml.yml
...